## Smart Grip Bar



In [1]:
# Standard library imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import seaborn as sns
from datetime import timedelta

In [2]:
# Read csv file
df = pd.read_csv('simulated_sensor.csv')
df.head(15)

Timestamp  Sensor1  Sensor2  Sensor3  Sensor4  Sensor5  Sensor6  Sensor7  \
0         0.0      0.4      0.8      1.0      0.9      0.6      0.5      0.3   
1         0.5      0.9      1.2      1.5      1.1      0.9      0.8      0.6   
2         1.0      0.9      1.2      1.3      0.9      0.8      0.5      0.4   
3         1.5      0.7      0.9      1.2      1.3      1.8      0.7      0.4   
4         2.0      0.9      1.1      1.3      0.8      0.8      0.7      0.3   
5         2.5      0.7      0.8      0.9      0.8      0.5      0.4      0.3   
6         3.0      0.3      0.3      0.4      0.7      0.8      0.9      0.9   
7         3.5      0.1      0.2      0.5      0.8      1.1      1.3      1.2   
8         4.0      0.7      0.8      0.9      1.2      1.3      0.8      0.9   
9         4.5      0.8      0.8      0.9      1.0      0.9      0.8      0.5   
10        5.0      0.5      0.9      0.8      0.9      0.8      0.5      0.3   
11        5.5      0.7      0.8      0.9      1.1      1.2      1.0      0.9   
12        6.0      0.8      0.9      1.0      0.9      0.9      0.8      0.7   
13        6.5      0.8      0.9      1.0      1.0      0.9      0.7      0.2   
14        7.0      0.8      0.9      1.0      1.0      0.9      0.7      0.3   

    Sensor8  Sensor9  Sensor10  Sensor11  Sensor12   Exercise  
0       0.4      0.1       0.0       0.2       0.3  Dead Hang  
1       0.5      0.0       0.0       0.2       0.3    Pull-Up  
2       0.4      0.4       0.5       0.6       0.6    Pull-Up  
3       0.3      0.5       0.6       0.7       0.8    Pull-Up  
4       0.3      0.4       0.5       0.5       0.6    Pull-Up  
5       0.1      0.1       0.3       0.4       0.7    Pull-Up  
6       0.6      0.5       0.3       0.2       0.2    Chin-Up  
7       0.9      0.5       0.2       0.1       0.1    Chin-Up  
8       0.8      0.6       0.5       0.4       0.4    Chin-Up  
9       0.3      0.2       0.2       0.3       0.3    Chin-Up  
10      0.2      0.1       0.2       0.3       0.2    Chin-Up  
11      0.8      0.7       0.6       0.4       0.5    Chin-Up  
12      0.4      0.2       0.2       0.3       0.6  Dead Hang  
13      0.2      0.2       0.3       0.4       0.5  Dead Hang  
14      0.2      0.2       0.3       0.4       0.8  Dead Hang

In [3]:
# Check initial exercise distribution
print(df['Exercise'].value_counts())
print("Number of rows: " , len(df))

Exercise
Chin-Up      6
Pull-Up      5
Dead Hang    4
Name: count, dtype: int64
Number of rows:  15


In [4]:
# Function to add Gaussian noise to the dataframe
def add_noise_to_dataframe(df, noise_level=0.01, num_synthetic_rows=100):
    df_with_noise = df.copy()  # Make a copy of the original dataframe
    
    # Identify numeric columns (assuming that all the sensor columns are numeric)
    numeric_columns = df.select_dtypes(include=np.number).columns
    
    # Create synthetic rows by adding noise
    synthetic_data = []
    
    for _ in range(num_synthetic_rows):
        # Choose a random row from the original dataframe
        random_row = df.sample(n=1)
        
        # Add Gaussian noise to each numeric column
        noisy_row = random_row.copy()
        for col in numeric_columns:
            noise = np.random.normal(0, noise_level, size=random_row[col].shape)
            noisy_row[col] = random_row[col] + noise
        
        # Append the noisy row to the synthetic data list
        synthetic_data.append(noisy_row)
    
    # Combine the original dataframe with the synthetic data
    synthetic_df = pd.concat(synthetic_data, ignore_index=True)
    
    return pd.concat([df, synthetic_df], ignore_index=True)

In [5]:
df_with_noise = add_noise_to_dataframe(df, noise_level=0.05, num_synthetic_rows=100)

# Check the new exercise distribution
print(df_with_noise['Exercise'].value_counts())
print("Number of rows: " , len(df_with_noise))

Exercise
Chin-Up      47
Pull-Up      42
Dead Hang    26
Name: count, dtype: int64
Number of rows:  115


In [6]:
df_with_noise.head(20)

Timestamp   Sensor1   Sensor2   Sensor3   Sensor4   Sensor5   Sensor6  \
0    0.000000  0.400000  0.800000  1.000000  0.900000  0.600000  0.500000   
1    0.500000  0.900000  1.200000  1.500000  1.100000  0.900000  0.800000   
2    1.000000  0.900000  1.200000  1.300000  0.900000  0.800000  0.500000   
3    1.500000  0.700000  0.900000  1.200000  1.300000  1.800000  0.700000   
4    2.000000  0.900000  1.100000  1.300000  0.800000  0.800000  0.700000   
5    2.500000  0.700000  0.800000  0.900000  0.800000  0.500000  0.400000   
6    3.000000  0.300000  0.300000  0.400000  0.700000  0.800000  0.900000   
7    3.500000  0.100000  0.200000  0.500000  0.800000  1.100000  1.300000   
8    4.000000  0.700000  0.800000  0.900000  1.200000  1.300000  0.800000   
9    4.500000  0.800000  0.800000  0.900000  1.000000  0.900000  0.800000   
10   5.000000  0.500000  0.900000  0.800000  0.900000  0.800000  0.500000   
11   5.500000  0.700000  0.800000  0.900000  1.100000  1.200000  1.000000   
12   6.000000  0.800000  0.900000  1.000000  0.900000  0.900000  0.800000   
13   6.500000  0.800000  0.900000  1.000000  1.000000  0.900000  0.700000   
14   7.000000  0.800000  0.900000  1.000000  1.000000  0.900000  0.700000   
15   0.931046  0.867234  1.267823  1.342492  0.918474  0.816902  0.551482   
16   0.578640  0.820382  1.214524  1.431538  1.041980  1.052009  0.833724   
17   4.490611  0.689671  0.824256  0.898628  1.034502  0.879602  0.837918   
18   1.032795  0.961354  1.170433  1.270635  0.921608  0.868558  0.478802   
19   0.438177  0.887288  1.186037  1.467230  1.156903  0.863083  0.856236   

     Sensor7   Sensor8   Sensor9  Sensor10  Sensor11  Sensor12   Exercise  
0   0.300000  0.400000  0.100000  0.000000  0.200000  0.300000  Dead Hang  
1   0.600000  0.500000  0.000000  0.000000  0.200000  0.300000    Pull-Up  
2   0.400000  0.400000  0.400000  0.500000  0.600000  0.600000    Pull-Up  
3   0.400000  0.300000  0.500000  0.600000  0.700000  0.800000    Pull-Up  
4   0.300000  0.300000  0.400000  0.500000  0.500000  0.600000    Pull-Up  
5   0.300000  0.100000  0.100000  0.300000  0.400000  0.700000    Pull-Up  
6   0.900000  0.600000  0.500000  0.300000  0.200000  0.200000    Chin-Up  
7   1.200000  0.900000  0.500000  0.200000  0.100000  0.100000    Chin-Up  
8   0.900000  0.800000  0.600000  0.500000  0.400000  0.400000    Chin-Up  
9   0.500000  0.300000  0.200000  0.200000  0.300000  0.300000    Chin-Up  
10  0.300000  0.200000  0.100000  0.200000  0.300000  0.200000    Chin-Up  
11  0.900000  0.800000  0.700000  0.600000  0.400000  0.500000    Chin-Up  
12  0.700000  0.400000  0.200000  0.200000  0.300000  0.600000  Dead Hang  
13  0.200000  0.200000  0.200000  0.300000  0.400000  0.500000  Dead Hang  
14  0.300000  0.200000  0.200000  0.300000  0.400000  0.800000  Dead Hang  
15  0.369150  0.366908  0.380458  0.506376  0.579068  0.566553    Pull-Up  
16  0.586380  0.476155  0.022856  0.038188  0.141232  0.263279    Pull-Up  
17  0.538747  0.350309  0.105813  0.039724  0.421258  0.259950    Chin-Up  
18  0.392544  0.450402  0.489001  0.570130  0.492233  0.590610    Pull-Up  
19  0.576354  0.518693  0.033026  0.064166  0.172455  0.286620    Pull-Up

### Machine Learning modeling
ML model classifies each exercise performed based on force sensor data. 
Below we try out different ML models that may be used.

In [7]:
# Data frame used by models
df_noise = df_with_noise.drop(columns = ["Timestamp"], axis =1)

#### Random Forest Classifier

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Encode the target variable 'Exercise'
le = LabelEncoder()
df_noise['Exercise_Label'] = le.fit_transform(df_noise['Exercise'])

# Features and target
X = df_noise.drop(columns=['Exercise', 'Exercise_Label'])
y = df_noise['Exercise_Label']

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Cross-validation
cv_scores_rf = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='accuracy')
print("Random Forest CV Accuracy Scores: ", cv_scores_rf)
print("Random Forest Average CV Accuracy: ", cv_scores_rf.mean())

# Train the model
rf_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_rf = rf_model.predict(X_test)
rf_test_accuracy = accuracy_score(y_test, y_pred_rf)
print("Random Forest Test Accuracy: ", rf_test_accuracy)


Random Forest CV Accuracy Scores:  [1.         0.89473684 1.         0.94444444 1.        ]
Random Forest Average CV Accuracy:  0.9678362573099415
Random Forest Test Accuracy:  0.9565217391304348


#### Decision Tree Classifier

In [9]:
from sklearn.tree import DecisionTreeClassifier

# Initialize Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)

# Cross-validation
cv_scores_dt = cross_val_score(dt_model, X_train, y_train, cv=5, scoring='accuracy')
print("Decision Tree CV Accuracy Scores: ", cv_scores_dt)
print("Decision Tree Average CV Accuracy: ", cv_scores_dt.mean())

# Train the model
dt_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_dt = dt_model.predict(X_test)
dt_test_accuracy = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Test Accuracy: ", dt_test_accuracy)


Decision Tree CV Accuracy Scores:  [1.         0.84210526 0.94444444 0.94444444 0.94444444]
Decision Tree Average CV Accuracy:  0.9350877192982457
Decision Tree Test Accuracy:  0.9565217391304348


#### Support Vector Machine (SVM)

In [10]:
from sklearn.svm import SVC

# Initialize SVM model
svm_model = SVC(random_state=42)

# Cross-validation
cv_scores_svm = cross_val_score(svm_model, X_train, y_train, cv=5, scoring='accuracy')
print("SVM CV Accuracy Scores: ", cv_scores_svm)
print("SVM Average CV Accuracy: ", cv_scores_svm.mean())

# Train the model
svm_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_svm = svm_model.predict(X_test)
svm_test_accuracy = accuracy_score(y_test, y_pred_svm)
print("SVM Test Accuracy: ", svm_test_accuracy)


SVM CV Accuracy Scores:  [0.94736842 0.78947368 0.94444444 0.94444444 1.        ]
SVM Average CV Accuracy:  0.9251461988304094
SVM Test Accuracy:  0.8260869565217391


#### Multilayer Perceptron (MLP) Classifier

In [11]:
from sklearn.neural_network import MLPClassifier

# Initialize MLP model
mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)

# Cross-validation
cv_scores_mlp = cross_val_score(mlp_model, X_train, y_train, cv=5, scoring='accuracy')
print("MLP CV Accuracy Scores: ", cv_scores_mlp)
print("MLP Average CV Accuracy: ", cv_scores_mlp.mean())

# Train the model
mlp_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_mlp = mlp_model.predict(X_test)
mlp_test_accuracy = accuracy_score(y_test, y_pred_mlp)
print("MLP Test Accuracy: ", mlp_test_accuracy)


MLP CV Accuracy Scores:  [1.         0.94736842 1.         1.         1.        ]
MLP Average CV Accuracy:  0.9894736842105264
MLP Test Accuracy:  0.9565217391304348


In [12]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import joblib

# Encode the target variable 'Exercise'
le = LabelEncoder()
df_noise['Exercise_Label'] = le.fit_transform(df_noise['Exercise'])

# Features and target
X = df_noise.drop(columns=['Exercise', 'Exercise_Label'])
y = df_noise['Exercise_Label']

# Split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost model
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# GridSearchCV to find best hyperparameters
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, 
                           scoring='accuracy', cv=5, verbose=1, n_jobs=-1)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best hyperparameters
print("Best Hyperparameters: ", grid_search.best_params_)

# Best model from GridSearchCV
best_model = grid_search.best_estimator_

# Predict and evaluate accuracy on the test set
y_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy with Best Model: ", test_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Classification Report: Precision, Recall, and F1-Score
class_report = classification_report(y_test, y_pred, target_names=le.classes_)
print("Classification Report:")
print(class_report)

# Save the final model
joblib.dump(best_model, 'xgb_model_final.pkl')
print("Model saved as xgb_model_final.pkl")


Fitting 5 folds for each of 72 candidates, totalling 360 fits


C:\Users\ishit\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [08:13:19] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best Hyperparameters:  {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.8}
Test Accuracy with Best Model:  1.0
Confusion Matrix:
[[11  0  0]
 [ 0  4  0]
 [ 0  0  8]]
Classification Report:
              precision    recall  f1-score   support

     Chin-Up       1.00      1.00      1.00        11
   Dead Hang       1.00      1.00      1.00         4
     Pull-Up       1.00      1.00      1.00         8

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23

Model saved as xgb_model_final.pkl
