## Smart Grip Bar



In [ ]:
# Standard library imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [94]:
# Read csv file
df = pd.read_csv('simulated_sensor.csv')
df.head()

Timestamp  Sensor1  Sensor2  Sensor3  Sensor4  Sensor5  Sensor6  Sensor7  \
0        0.0      0.4      0.8      1.0      0.9      0.6      0.5      0.3   
1        0.5      0.9      1.2      1.5      1.1      0.9      0.8      0.6   
2        1.0      0.9      1.2      1.3      0.9      0.8      0.5      0.4   
3        1.5      0.7      0.9      1.2      1.3      1.8      0.7      0.4   
4        2.0      0.9      1.1      1.3      0.8      0.8      0.7      0.3   

   Sensor8  Sensor9  Sensor10  Sensor11  Sensor12   Exercise  
0      0.4      0.1       0.0       0.2       0.3  Dead Hang  
1      0.5      0.0       0.0       0.2       0.3    Pull-Up  
2      0.4      0.4       0.5       0.6       0.6    Pull-Up  
3      0.3      0.5       0.6       0.7       0.8    Pull-Up  
4      0.3      0.4       0.5       0.5       0.6    Pull-Up

In [95]:
# Check initial exercise distribution
print(df['Exercise'].value_counts())
print("Number of rows: " , len(df))

Exercise
Chin-Up      6
Pull-Up      5
Dead Hang    4
Name: count, dtype: int64
Number of rows:  15


In [96]:
# Function to add Gaussian noise to the dataframe
def add_noise_to_dataframe(df, noise_level=0.1, num_synthetic_rows=100):
    df_with_noise = df.copy()  # Make a copy of the original dataframe
    
    # Identify numeric columns (assuming that all the sensor columns are numeric)
    numeric_columns = df.select_dtypes(include=np.number).columns
    
    # Create synthetic rows by adding noise
    synthetic_data = []
    
    for _ in range(num_synthetic_rows):
        # Choose a random row from the original dataframe
        random_row = df.sample(n=1)
        
        # Add Gaussian noise to each numeric column
        noisy_row = random_row.copy()
        for col in numeric_columns:
            noise = np.random.normal(0, noise_level, size=random_row[col].shape)
            noisy_row[col] = random_row[col] + noise
        
        # Append the noisy row to the synthetic data list
        synthetic_data.append(noisy_row)
    
    # Combine the original dataframe with the synthetic data
    synthetic_df = pd.concat(synthetic_data, ignore_index=True)
    
    return pd.concat([df, synthetic_df], ignore_index=True)

In [106]:
df_with_noise = add_noise_to_dataframe(df, noise_level=0.1, num_synthetic_rows=100)

# Check the new exercise distribution
print(df_with_noise['Exercise'].value_counts())
print("Number of rows: " , len(df_with_noise))

Exercise
Chin-Up      50
Pull-Up      34
Dead Hang    31
Name: count, dtype: int64
Number of rows:  115


In [107]:
df_with_noise.head(20)

Timestamp   Sensor1   Sensor2   Sensor3   Sensor4   Sensor5   Sensor6  \
0    0.000000  0.400000  0.800000  1.000000  0.900000  0.600000  0.500000   
1    0.500000  0.900000  1.200000  1.500000  1.100000  0.900000  0.800000   
2    1.000000  0.900000  1.200000  1.300000  0.900000  0.800000  0.500000   
3    1.500000  0.700000  0.900000  1.200000  1.300000  1.800000  0.700000   
4    2.000000  0.900000  1.100000  1.300000  0.800000  0.800000  0.700000   
5    2.500000  0.700000  0.800000  0.900000  0.800000  0.500000  0.400000   
6    3.000000  0.300000  0.300000  0.400000  0.700000  0.800000  0.900000   
7    3.500000  0.100000  0.200000  0.500000  0.800000  1.100000  1.300000   
8    4.000000  0.700000  0.800000  0.900000  1.200000  1.300000  0.800000   
9    4.500000  0.800000  0.800000  0.900000  1.000000  0.900000  0.800000   
10   5.000000  0.500000  0.900000  0.800000  0.900000  0.800000  0.500000   
11   5.500000  0.700000  0.800000  0.900000  1.100000  1.200000  1.000000   
12   6.000000  0.800000  0.900000  1.000000  0.900000  0.900000  0.800000   
13   6.500000  0.800000  0.900000  1.000000  1.000000  0.900000  0.700000   
14   7.000000  0.800000  0.900000  1.000000  1.000000  0.900000  0.700000   
15   4.436914  0.595180  0.823296  1.074957  0.991803  0.834502  0.533603   
16   4.531184  0.678688  0.689182  0.917546  1.007349  0.958604  0.798103   
17  -0.038279  0.294588  0.738819  0.940797  1.058163  0.706370  0.550194   
18   3.119200  0.376190  0.136839  0.333350  0.715008  0.781750  0.881013   
19   2.590004  0.834618  0.804051  1.037676  0.849458  0.685859  0.512775   

     Sensor7   Sensor8   Sensor9  Sensor10  Sensor11  Sensor12   Exercise  
0   0.300000  0.400000  0.100000  0.000000  0.200000  0.300000  Dead Hang  
1   0.600000  0.500000  0.000000  0.000000  0.200000  0.300000    Pull-Up  
2   0.400000  0.400000  0.400000  0.500000  0.600000  0.600000    Pull-Up  
3   0.400000  0.300000  0.500000  0.600000  0.700000  0.800000    Pull-Up  
4   0.300000  0.300000  0.400000  0.500000  0.500000  0.600000    Pull-Up  
5   0.300000  0.100000  0.100000  0.300000  0.400000  0.700000    Pull-Up  
6   0.900000  0.600000  0.500000  0.300000  0.200000  0.200000    Chin-Up  
7   1.200000  0.900000  0.500000  0.200000  0.100000  0.100000    Chin-Up  
8   0.900000  0.800000  0.600000  0.500000  0.400000  0.400000    Chin-Up  
9   0.500000  0.300000  0.200000  0.200000  0.300000  0.300000    Chin-Up  
10  0.300000  0.200000  0.100000  0.200000  0.300000  0.200000    Chin-Up  
11  0.900000  0.800000  0.700000  0.600000  0.400000  0.500000    Chin-Up  
12  0.700000  0.400000  0.200000  0.200000  0.300000  0.600000  Dead Hang  
13  0.200000  0.200000  0.200000  0.300000  0.400000  0.500000  Dead Hang  
14  0.300000  0.200000  0.200000  0.300000  0.400000  0.800000  Dead Hang  
15  0.307922  0.210713  0.098957  0.318144  0.428317  0.304548    Chin-Up  
16  0.451375  0.276245  0.120406  0.180742  0.182369  0.200825    Chin-Up  
17  0.253794  0.361536  0.101426 -0.087966  0.374776 -0.066339  Dead Hang  
18  0.867176  0.618887  0.800582  0.456925  0.078814  0.108428    Chin-Up  
19  0.137452  0.128661  0.029051  0.496285  0.356567  0.750963    Pull-Up

### Machine Learning modeling
ML model classifies each exercise performed based on force sensor data. 
Below we try out different ML models that may be used.

In [108]:
# Data frame used by models
df_noise = df_with_noise.drop(columns = ["Timestamp"], axis = 1)

#### Random Forest Classifier

In [109]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Encode the target variable 'Exercise'
le = LabelEncoder()
df_noise['Exercise_Label'] = le.fit_transform(df_noise['Exercise'])

# Features and target
X = df_noise.drop(columns=['Exercise', 'Exercise_Label'])
y = df_noise['Exercise_Label']

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Cross-validation
cv_scores_rf = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='accuracy')
print("Random Forest CV Accuracy Scores: ", cv_scores_rf)
print("Random Forest Average CV Accuracy: ", cv_scores_rf.mean())

# Train the model
rf_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_rf = rf_model.predict(X_test)
rf_test_accuracy = accuracy_score(y_test, y_pred_rf)
print("Random Forest Test Accuracy: ", rf_test_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_rf)
print("Confusion Matrix:")
print(cm)

# Classification Report: Precision, Recall, and F1-Score
class_report = classification_report(y_test, y_pred_rf, target_names=le.classes_)
print("Classification Report:")
print(class_report)


Random Forest CV Accuracy Scores:  [0.84210526 0.84210526 0.94444444 1.         1.        ]
Random Forest Average CV Accuracy:  0.9257309941520468
Random Forest Test Accuracy:  0.9565217391304348
Confusion Matrix:
[[9 0 0]
 [1 6 0]
 [0 0 7]]
Classification Report:
              precision    recall  f1-score   support

     Chin-Up       0.90      1.00      0.95         9
   Dead Hang       1.00      0.86      0.92         7
     Pull-Up       1.00      1.00      1.00         7

    accuracy                           0.96        23
   macro avg       0.97      0.95      0.96        23
weighted avg       0.96      0.96      0.96        23



#### Decision Tree Classifier

In [101]:
from sklearn.tree import DecisionTreeClassifier

# Initialize Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)

# Cross-validation
cv_scores_dt = cross_val_score(dt_model, X_train, y_train, cv=5, scoring='accuracy')
print("Decision Tree CV Accuracy Scores: ", cv_scores_dt)
print("Decision Tree Average CV Accuracy: ", cv_scores_dt.mean())

# Train the model
dt_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_dt = dt_model.predict(X_test)
dt_test_accuracy = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Test Accuracy: ", dt_test_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_dt)
print("Confusion Matrix:")
print(cm)

# Classification Report: Precision, Recall, and F1-Score
class_report = classification_report(y_test, y_pred_dt, target_names=le.classes_)
print("Classification Report:")
print(class_report)


Decision Tree CV Accuracy Scores:  [0.89473684 0.84210526 0.88888889 0.72222222 0.83333333]
Decision Tree Average CV Accuracy:  0.8362573099415205
Decision Tree Test Accuracy:  0.8695652173913043
Confusion Matrix:
[[7 2 0]
 [0 7 0]
 [1 0 6]]
Classification Report:
              precision    recall  f1-score   support

     Chin-Up       0.88      0.78      0.82         9
   Dead Hang       0.78      1.00      0.88         7
     Pull-Up       1.00      0.86      0.92         7

    accuracy                           0.87        23
   macro avg       0.88      0.88      0.87        23
weighted avg       0.88      0.87      0.87        23



#### Support Vector Machine (SVM)

In [102]:
from sklearn.svm import SVC

# Initialize SVM model
svm_model = SVC(random_state=42)

# Cross-validation
cv_scores_svm = cross_val_score(svm_model, X_train, y_train, cv=5, scoring='accuracy')
print("SVM CV Accuracy Scores: ", cv_scores_svm)
print("SVM Average CV Accuracy: ", cv_scores_svm.mean())

# Train the model
svm_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_svm = svm_model.predict(X_test)
svm_test_accuracy = accuracy_score(y_test, y_pred_svm)
print("SVM Test Accuracy: ", svm_test_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_svm)
print("Confusion Matrix:")
print(cm)

# Classification Report: Precision, Recall, and F1-Score
class_report = classification_report(y_test, y_pred_svm, target_names=le.classes_)
print("Classification Report:")
print(class_report)


SVM CV Accuracy Scores:  [0.78947368 0.89473684 0.94444444 0.88888889 1.        ]
SVM Average CV Accuracy:  0.9035087719298247
SVM Test Accuracy:  0.8695652173913043
Confusion Matrix:
[[6 3 0]
 [0 7 0]
 [0 0 7]]
Classification Report:
              precision    recall  f1-score   support

     Chin-Up       1.00      0.67      0.80         9
   Dead Hang       0.70      1.00      0.82         7
     Pull-Up       1.00      1.00      1.00         7

    accuracy                           0.87        23
   macro avg       0.90      0.89      0.87        23
weighted avg       0.91      0.87      0.87        23



#### Multilayer Perceptron (MLP) Classifier

In [103]:
from sklearn.neural_network import MLPClassifier

# Initialize MLP model
mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)

# Cross-validation
cv_scores_mlp = cross_val_score(mlp_model, X_train, y_train, cv=5, scoring='accuracy')
print("MLP CV Accuracy Scores: ", cv_scores_mlp)
print("MLP Average CV Accuracy: ", cv_scores_mlp.mean())

# Train the model
mlp_model.fit(X_train, y_train)

# Predict and evaluate accuracy on test set
y_pred_mlp = mlp_model.predict(X_test)
mlp_test_accuracy = accuracy_score(y_test, y_pred_mlp)
print("MLP Test Accuracy: ", mlp_test_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_mlp)
print("Confusion Matrix:")
print(cm)

# Classification Report: Precision, Recall, and F1-Score
class_report = classification_report(y_test, y_pred_mlp, target_names=le.classes_)
print("Classification Report:")
print(class_report)


C:\Users\ishit\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLP CV Accuracy Scores:  [0.84210526 1.         0.94444444 1.         0.88888889]
MLP Average CV Accuracy:  0.9350877192982455
MLP Test Accuracy:  0.9565217391304348
Confusion Matrix:
[[8 1 0]
 [0 7 0]
 [0 0 7]]
Classification Report:
              precision    recall  f1-score   support

     Chin-Up       1.00      0.89      0.94         9
   Dead Hang       0.88      1.00      0.93         7
     Pull-Up       1.00      1.00      1.00         7

    accuracy                           0.96        23
   macro avg       0.96      0.96      0.96        23
weighted avg       0.96      0.96      0.96        23



#### XG Boost

In [104]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import joblib

# # Encode the target variable 'Exercise'
# le = LabelEncoder()
# df_noise['Exercise_Label'] = le.fit_transform(df_noise['Exercise'])

# # Features and target
# X = df_noise.drop(columns=['Exercise', 'Exercise_Label'])
# y = df_noise['Exercise_Label']

# # Split the data into train and test
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost model
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# GridSearchCV to find best hyperparameters
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, 
                           scoring='accuracy', cv=5, verbose=1, n_jobs=-1)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best hyperparameters
print("Best Hyperparameters: ", grid_search.best_params_)

# Best model from GridSearchCV
best_model = grid_search.best_estimator_

# Predict and evaluate accuracy on the test set
y_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy with Best Model: ", test_accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Classification Report: Precision, Recall, and F1-Score
class_report = classification_report(y_test, y_pred, target_names=le.classes_)
print("Classification Report:")
print(class_report)

# Save the final model
joblib.dump(best_model, 'xgb_model_final.pkl')
print("Model saved as xgb_model_final.pkl")


Fitting 5 folds for each of 72 candidates, totalling 360 fits


C:\Users\ishit\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [08:46:40] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best Hyperparameters:  {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100, 'subsample': 0.8}
Test Accuracy with Best Model:  0.9565217391304348
Confusion Matrix:
[[8 1 0]
 [0 7 0]
 [0 0 7]]
Classification Report:
              precision    recall  f1-score   support

     Chin-Up       1.00      0.89      0.94         9
   Dead Hang       0.88      1.00      0.93         7
     Pull-Up       1.00      1.00      1.00         7

    accuracy                           0.96        23
   macro avg       0.96      0.96      0.96        23
weighted avg       0.96      0.96      0.96        23

Model saved as xgb_model_final.pkl
